### ISSUE TITLE
Theme's color palette should come from the project's logo

### ISSUE THREAD

**Issue by dimitrisnl** [balena-io/landr#138]
> Original idea by @jviotti 	

- Extract colors using something like https://jariz.github.io/vibrant.js/
- Update the primary/secondary/tertiary/quaternary colors of rendition's theme

One thing that's unclear is how is the image/logo provided.
Github offers a `social preview` option that we could use.

![Screen Shot 2019-06-25 at 2 59 56 PM](https://user-images.githubusercontent.com/4951004/60096564-f3d1b080-9759-11e9-921e-80651b040854.png)

**Comment by jviotti** [comment]
For reference: https://web.archive.org/web/20160609141148/http://blog.dabbledb.com/2007/04/white--or-green.html
