### ISSUE TITLE
Improve Markdown renderer in DocViewer

### ISSUE THREAD

**Issue by jviotti** [balena-io/landr#171]
Seems like it can't handle things such as:

- A language after the triple back ticks
- Back ticks in titles
- Markdown tables
- Images

We have the data correctly represented as JSONML, so we probably just need a better JSONML to markdown (or HTML) module.

Some examples:

<img width="1038" alt="Screenshot 2019-07-08 at 18 46 16" src="https://user-images.githubusercontent.com/2192773/60831127-b7b63b00-a1b0-11e9-893e-91a5f30f4a4f.png">

<img width="1439" alt="Screenshot 2019-07-08 at 18 46 08" src="https://user-images.githubusercontent.com/2192773/60831117-b258f080-a1b0-11e9-88d2-4f4bd642bf85.png">

**Comment by dimitrisnl** [comment]
Seems like this is a limitation by the library https://github.com/evilstreak/markdown-js/issues/41

They don't support this syntax, and the project is un unmaintained.

Needs to find a working alternative that hopefully has some jsonml helpers too.

**Comment by dimitrisnl** [comment]
@jviotti 	Can you remind me how to generate/update meta.json?

The jsonML object has parsed the table as a string 

```
              [
                "para",
                "| Arguments | Description | Optional? | Default |\n|-----------|-------------|-----------|---------|\n| ",
                [
                  "inlinecode",
                  "[meta.json]"
                ],
                " | Path to ",
                [
                  "inlinecode",
                  "meta.json"
                ],
                " | Y | ",
                [
                  "inlinecode",
                  "$PWD/meta.json"
                ],
                " |"
              ],
```

**Comment by jviotti** [comment]
@dimitrisnl we need to fix it here: https://github.com/balena-io/landr/blob/master/scripts/scrutinizer-stub.js

**Comment by dimitrisnl** [comment]
Should be addressed by this PR https://github.com/balena-io/landr/pull/264
