### ISSUE TITLE
Update the "good first issues" link to use GH first issue feature

### ISSUE THREAD

**Issue by jviotti** [balena-io/landr#178]
We can link to https://github.com/balena-io/landr/contribute, where GitHub renders a list of the good first issues it detected using a much smarter algorithm.

**Comment by dimitrisnl** [comment]
@jviotti 	The link is broken, is there a function that GH selects issues from your backlog?

**Comment by dimitrisnl** [comment]
I can only find this one https://github.com/topics/good-first-issue but it's a generic aggregator

**Comment by jviotti** [comment]
@dimitrisnl I fixed the link above:

<img width="1552" alt="Screenshot 2019-07-11 at 13 46 42" src="https://user-images.githubusercontent.com/2192773/61051988-52e22700-a3e2-11e9-94d9-8dc0c40c3be2.png">
