### ISSUE TITLE
Render alert on contributing guide mentioning CODEOWNERS

### ISSUE THREAD

**Issue by jviotti** [balena-io/landr#179]
Add an alert at the bottom of the contributing doc saying something like: "if you need any help, please ping @<user>, @<user>, or @<user>", where the users are the handles on CODEOWNERS, which we already parse in meta.json.

**Comment by dimitrisnl** [comment]
We don't parse codeowners just yet, can you please remind me how to update meta.json?

**Comment by jviotti** [comment]
@dimitrisnl You can update https://github.com/balena-io/landr/blob/master/scripts/scrutinizer-stub.js and then run `node scripts/scrutinizer-stub.js > meta.json`

**Comment by jviotti** [comment]
@dimitrisnl Looks like we already do this: https://github.com/balena-io/landr/blob/master/scripts/scrutinizer-stub.js#L155

**Comment by dimitrisnl** [comment]
Ah great, it was under maintaners
