### ISSUE TITLE
Typo in README?

### ISSUE THREAD

**Issue by lurch** [balena-io/landr#187]
It says "The Landr website is of course based on Land!"

Should the `Land` be `Landr`? :joy:

**Comment by jviotti** [comment]
Great catch! Nice to see you around :) Here's a PR: https://github.com/balena-io/landr/pull/192

**Comment by lurch** [comment]
I was also curious why the Landr website is https://www.versionbot.com/ ? Seems to have no connection to the URL, but I'm sure there must be some (hidden) reason for it :wink:

**Comment by jviotti** [comment]
@lurch We were demo-ing Netlify's branch preview deploys features, which requires a custom domain, and we had versionbot.com at hand, while we do not own any landr domain. In any case, we may host landr in versionbot.com/landr as part of a versionbot project umbrella.
