### ISSUE TITLE
Changing between versions in docs isn't working

### ISSUE THREAD

**Issue by dimitrisnl** [balena-io/landr#196]
The routing works, it just seems that the paths are not generated.

![Screen Shot 2019-07-11 at 2 33 13 PM](https://user-images.githubusercontent.com/4951004/61047776-e7e81e80-a3e8-11e9-92a6-945ce3c031b8.png)

**Comment by dimitrisnl** [comment]
![Screen Shot 2019-07-11 at 2 35 59 PM](https://user-images.githubusercontent.com/4951004/61047926-38f81280-a3e9-11e9-975b-495a94aae4de.png)

That being said the HTML files exist

**Comment by jviotti** [comment]
@dimitrisnl This sounds like a `serve` thing.  Does it work on Netlify? https://www.versionbot.com/docs/cli/0.1.1/ works for me

**Comment by jviotti** [comment]
If that's the case then we can maybe use and suggest another static server for development purposes?

**Comment by dimitrisnl** [comment]
@jviotti 	Makes sense. I'll strip down the PR and keep the parts that fix these incorrect paths (https://www.versionbot.com/docs/cli/0.1.1/0.1.1).

**Comment by dimitrisnl** [comment]
https://www.npmjs.com/package/http-server Works fine with dots
