### ISSUE TITLE
Shorten build time

### ISSUE THREAD

**Issue by dimitrisnl** [balena-io/landr#210]
As we add more components & combinations the build time increases by a lot.

Commenting out combinations/routes as a temporary hack, add the danger of committing these changes, as these changes span across many files.

**Comment by dimitrisnl** [comment]
cc @jviotti

**Comment by dimitrisnl** [comment]
Might be also a good idea to strip React static as it's deprecated. No reason to look for optimizations there.

**Comment by dimitrisnl** [comment]
@jviotti 	Any thoughts? Commenting out combinations & routes doesn't help any more. There's the danger of committing these changes. We have to address this since the development get's very difficult.

**Comment by jviotti** [comment]
@dimitrisnl Have we added more components? I'll focus on this tomorrow

**Comment by dimitrisnl** [comment]
The last one is the motivation one @jviotti

**Comment by dimitrisnl** [comment]
@jviotti 	Did you have the chance to explore any options?
