### ISSUE TITLE
linked to site generates error

### ISSUE THREAD

**Issue by simbo1905** [balena-io/landr#228]
I click on the site linked to at the top of the repo "https://www.versionbot.com" in either google chrome or safari and I see a page for a few seconds then it is replaced with this text: 
 
An error occurred loading this page's template. More information is available in the console.

**Comment by dimitrisnl** [comment]
Hey there @simbo1905 	This is a nasty bug introduced in React-static `7.2.0`. For now, we've pinned the dependency to `7.1.0` and will upgrade when it's been resolved.

Thanks!
