### ISSUE TITLE
Allow the user to define custom pages from within www/

### ISSUE THREAD

**Issue by jviotti** [balena-io/landr#77]
If I place a file called `www/foo.jsx`, containing a React component, then Landr should use that component to render a route called `/foo`.

**Comment by jviotti** [comment]
Notice this is related to https://github.com/resin-io/landr/issues/76. The rule is the following:

- If something inside `www` has a `jsx` extension, then its compiled as a route
- If not, its copied as-is

**Comment by craig-mulligan** [comment]
Each theme should export components from an entry file.
